### ISSUE TITLE
Update the ReadMe file to show steps for setting up Dev environment.

### ISSUE THREAD

**Issue by gbozee** [pyung/pyconng#3]
Currently the ReadMe file is showing some stale information on how to successfully set up the development environment.

It would need to be updated. To ensure that everyone's development environment is as similar as possible, Docker and docker-compose are used to bootstrap the dev environemnt. Docker would also be used in production.

Completing this issue involves two task

1. Trying to setup a development environment and 
2. Documenting the steps involved.

Requirements
1. Installation of docker and docker-compose.

Caveats
Because some of the docker images are kinda large, it might take a chunk out of people's internet connection. Work would be done to ensure smaller docker images are being used.

**Comment by Olamyy** [comment]
I'm currently looking into this.
However, I seem to be getting an error from docker that a **new.env**  file is missing.
Should I guess that the env file is to be created from the env.example file?

**Comment by gbozee** [comment]
Okay what specific error are you running into. There are two configuration files. 
1. `dev.yml` which is for development and 
2. `docker-compose.yml` which is for production.

All the configuration for development should still be there. We would try as much as possible to avoid adding Secrets to the `.env`

**Comment by wolejnr** [comment]
I'll work to set up the development environment on my Mac and highlight any areas that require updates in the readme file

**Comment by gbozee** [comment]
Cool. If your run into any issues please feel free to raise an issue

**Comment by Olamyy** [comment]
As an update, I have successfully been able to setup the project locally on my device.
However, one problem I had was postgresql. For some reasons, I have more than one postgre installation and they seem to be clashing or something.
Anyway, I've switched my local db to mysql for the meantime till I get the postgre fixed.

**Comment by gbozee** [comment]
If you are using docker, you could install postgres in a docker container instead.

**Comment by Olamyy** [comment]
Alright. Thanks. I'd look into this.

**Comment by gbozee** [comment]
Any reason why this was closed since it hasn't been merged yet to the master branch?

**Comment by Olamyy** [comment]
Yeah. Sorry. That was an error from my end.

**Comment by jattoabdul** [comment]
@Olamyy and @wolejnr Is there any update for us on the application development environment setup and can we update the readme ASAP to help anyone currently blocked with setting up?

**Comment by gbozee** [comment]
For anyone willing to update the readme, here are the steps i took to get the project up and running

This setup assumes docker and docker-compose are installed.
```
$ git clone git@github.com:pyung/pyconng.git
$ git checkout archive/2017  # this is the 2017 code base
$ docker-compose -f dev.yml up -d
```
Since the database would be empty, a dump is provided a the discussion channel. https://github.com/orgs/pyung/teams/development-team/discussions/1

**Comment by gbozee** [comment]
We would be building on top of this codebase so it is a good idea for everyone working on the backend to get familiar with this.
@adekoder @teenoh @Olamyy @Cimmanuel

**Comment by teenoh** [comment]
Quick question.....Are we working directly on the repo(different branches) or we are to fork the repo, and make PRs from there?

**Comment by wolejnr** [comment]
I guess we would be working on the develop branch. Simply follow the steps
in the ReadMe file to set up the development environment on your system.
You can also raise an issue if you encounter challenges in the setup
process.

**Comment by gbozee** [comment]
@teenoh we would be forking off the develop branch and then making PRs from there. That is exactly how we would be working.

**Comment by gbozee** [comment]
The steps to replicate the dev environment is available at https://github.com/gbozee/pyconng/tree/develop. I have updated the dependcies and pinned them so that it would be difficult to run into issues.

I would be closing this issue now.
