### ISSUE TITLE
Early bird ticket

### ISSUE THREAD

**Issue by Ochuwa-sophie** [pyung/pyconng#32]
Just noticed that the price for the earlybird ticket for students is in strikethrough. I don't know if this is a mistake or early bird registration for students is actually over.
![screenshot_20180831-031955](https://user-images.githubusercontent.com/25169298/44889604-6440aa00-acce-11e8-94e5-f9654f773391.png)
![screenshot_20180831-031636](https://user-images.githubusercontent.com/25169298/44889607-67d43100-acce-11e8-8316-6658d6a73747.png)

**Comment by shante66** [comment]
Hi Sophie, it's not an error, this means that the student early bird tickets are sold out, and since switched to normal prices
