### ISSUE TITLE
Error when trying to install application dependencies

### ISSUE THREAD

**Issue by wolejnr** [pyung/pyconng#5]
I am using Mac OSX 10.13.1. I get this error
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/hd/rwqx7l594ps9pcyc_cmsz82r0000gn/T/pip-build-xkv2au6m/psycopg2/
when I run 
`(venv)$ pip install -r requirements/local.txt`
The error message reads thus:
> Error:  pg_config executable not found. 
    Please add the directory containing pg_config to the PATH
    or specify the full executable path with the option:
    
        python setup.py build_ext --pg-config /path/to/pg_config build ...
    
    or with the pg_config option in 'setup.cfg'.

**Comment by gbozee** [comment]
what is the version of `psycopg2` in the `requirements.local.txt`?

**Comment by gbozee** [comment]
also do you have postgresql installed?

**Comment by wolejnr** [comment]
The `psycopg2` version is `2.6.2`
Also, I have not installed PostgreSQL yet

**Comment by gbozee** [comment]
try using the latest version of psycopg2 whichis 2.7.2 or so.

**Comment by wolejnr** [comment]
I have updated `psycopg2` to the latest version 2.7.3.2. I also installed postgresql and now I am getting this error
> Error: could not determine PostgreSQL version from '10.1'

I am still working at figuring it out

**Comment by gbozee** [comment]
can you find out what postgres version you installed. I think you should try installing 9.6 though

**Comment by wolejnr** [comment]
I finally figured it out. The reason why I was getting the error was that although I installed a newer version of `psycopg2`, I did not change the value in `requirements/base.txt` to reflect the new version which in my case is `2.7.1`. Thanks for your help.
